env:
  email: foo@gmail.com
  password: foo

persistentVolume:
  enabled: true
  size: 5Gi

service:
  type: NodePort
  port: 80
  nodePort: 32222 # <- http://foo.lan:32222

serverDefinitions:
  enabled: true
  servers:
    main:
      Name: "Main PostgreSQL"
      Group: "Databases"
      Host: "postgresql.postgresql.svc.cluster.local"
      Port: 5432
      Username: "foo"
      MaintenanceDB: "foo"
      SSLMode: "prefer"
