repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: postgresql
    namespace: postgresql
    chart: bitnami/postgresql
    values:
      - ./pgsql/values.yaml