repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: runix
    url: https://helm.runix.net/

releases:
  - name: postgresql
    namespace: postgresql
    chart: bitnami/postgresql
    values:
      - ./pgsql/values.yaml

  - name: pgadmin
    namespace: postgresql
    chart: runix/pgadmin4
    values:
      - ./pgsql-admin/values.yaml